Lambda-School-Labs/omega2020-be

- api/server.js
This changes the new data science endpoint so it starts at just /puzzle, a bit prettier and more intuiitive
> Changes Endpoint

- data_science/data-science-puzzles-router.js
- index.js
Adds an endpoint to provide the FE with a puzzle one input away from being solved, this is for the purpose of testing win state
> Testing Endpoint

- pull_request_template.md
adding a general PR template to use
Example:
> creating pull request template

- data_science/data-science-puzzles-router.js
Updated connectionString in data_science/data-science-puzzles-router.js
The connection was changed during the handoff, and this change includes the new address to the DS database. I ran the server locally, and the app no longer crashed.
Restored connection to Data Science database
> Restore DS connection string

- data_science/data-science-puzzles-router.js
Added endpoint for 4x4 puzzles
> Added endpoint for 4x4_puzzles from DS

- data_science/data-science-puzzles-router.js
> Commented out 6x6 and 9x9x

- api/configure-middleware.js
- package.json
Hertoku deployment appeared to crash with error message "module not found". Removed morgan.
> Removed morgan middleware

- database/dbconfig.js
> Restored dbconfig file

- data_science/data-science-puzzles-router.js
4x4 endpoint causing app to crash. Added "sudoku" to query string. That should fix it.
> Bug fix: fix 4x4 endpoint

- data_science/data-science-puzzles-router.js
Corrected queries on endpoints for table changes
Fixes non-working queries
> Corrected queries on endpoints for table changes

- api/server.js
- auth/auth.test.js
- data_science/data-science-puzzles-router.js
Added error handling to currently-working endpoints.
App would crash upon server errors. Attempting to correct this. This branch should probably have been called a bug fix, rather than a feature.
> Bug fix-Feature/error handling added to endpoints

- README.md
Updated README file to reflect all currently-working endpoints
/4x4/easy and /6x6/easy endpoints added.
> Updated README endpoints

- README.md
Corrected punctuation in README.md
Fixes incorrect formatting in README.md
> Corrected punctuation in README.md

- data_science/data-science-puzzles.test.js
Refactored to less than 250 lines, as required by Code Climate. Also, the original testing was leaving open handles. This has been corrected.
Too many lines
Open handles
> Refactored to less lines, per code climate, and no open handles detected in testing

- auth/auth-router.js
- knexfile.js
Fixed registration/login not working locally.
> Updated node modules, register/login now working

- knexfile.js
Trying to fix remote register/login issues
> Changed production env variables

- auth/auth-router.js
- database/dbconfig.js
- knexfile.js
Still working on register/login
> Connected with Heroku db locally

- knexfile.js
Trying to fix SSL issues on Heroku.
> Changed SSL to { rejectUnauthorized: false }

- api/configure-middleware.js
Attempting to fix CORS issue on upload
> Added corsOptions

- api/configure-middleware.js
> Removed corsOptions

- user_puzzles/user-puzzles-model.js
- user_puzzles/user-puzzles-router.js
- user_puzzles/user-puzzles.test.js
POST and GET userPuzzles working locally
> POST and GET userPuzzles working locally
